name: brave
version: v0.55.22dev
summary: Browse faster and safer with Brave.
description: |
 The new Brave browser automatically blocks ads and trackers, making it
 faster and safer than your current browser. Start supporting publishers
 today with our new Brave Payments system.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  
parts:
  brave:
    plugin: dump
    source: https://github.com/brave/brave-browser/releases/download/v0.55.22/brave-browser_0.55.22_amd64.deb
    source-type: deb
    # Correct path to icon.
    override-pull: |
      snapcraftctl pull  && rm -rf etc/cron.daily/ &&  rm -rf usr/bin/brave-browser
    after:
      - desktop-gtk3
    stage-packages:
      - gir1.2-gnomekeyring-1.0
      - libasound2
      - libgconf-2-4
      - libgl1-mesa-glx
      - libglu1-mesa
      - libgnome-keyring0
      - libcap2
      - libgcrypt20
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxtst6
      - libxss1

apps:
  brave:
    command: bin/desktop-launch $SNAP/usr/bin/brave --no-sandbox
    # Correct the TMPDIR path for Chromium Framework/Electron to
    # ensure libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - alsa
      - avahi-observe
#     - browser-sandbox
      - browser-support
      - desktop
      - desktop-legacy
      - camera
      - cups-control
      - gsettings
      - home
      - mount-observe
      - network
      - opengl
      - pulseaudio
      - screen-inhibit-control
      - unity7
      - upower-observe
      - wayland

#plugs:
#  browser-sandbox:
#    interface: browser-support
#    allow-sandbox: true
plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
